apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.metadata.name }}
  namespace: {{ .Values.certificate.metadata.namespace }}
spec:
  secretName: {{ .Values.certificate.spec.secretName }}
  commonName: {{ .Values.certificate.spec.commonName }}
  dnsNames:
  - {{ .Values.certificate.spec.dnsName }}
  - {{ .Values.certificate.spec.commonName }}
  issuerRef:
    name: {{ .Values.certificate.spec.issuerRef.name }}
    kind: Issuer