- name: add-node-to-cluster
  hosts: manager
  become: yes
  tasks:
    - name: Build /etc/hosts
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ceph_ip }} {{item}}" state=present
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups['all'] }}"
    - name: Create known_hosts
      file:
        path: /home/cephuser/.ssh/known_hosts
        state: touch
    - name: SSH scan all host keys
      loop: "{{ groups['workers'] }}"
      command: ssh-keyscan -t rsa {{ item }} >> /home/cephuser/.ssh/known_hosts

    - name: Check if nodes added to cluster
      command: ceph orch host ls
      register: cephhostlist
      ignore_errors: true
    - name: Add nodes to ceph cluster
      command: ceph orch host add {{ item }} {{ hostvars[item].ansible_host }}
      loop: "{{ groups['workers'] }}"
      when: cephhostlist.stdout.find(item) == -1

    - name: Apply OSD to all unpartitioned devices
      command: ceph orch apply osd --all-available-devices

    - name: Check current CephFS volumes
      command: ceph fs volume ls
      register: cephfslist
      ignore_errors: true
    - name: Create CephFS volume
      command: ceph fs volume create storage
      when: cephfslist.stdout.find("storage") == -1

    - name: Wait for CephFS volume availability
      command: ceph -s
      register: ceph_status_output
      until: ceph_status_output.stdout.find("HEALTH_OK") != -1
      retries: 30
      delay: 45

- name: manager-mount-fs
  hosts: manager
  become: yes
  tasks:
    - name: Create commad-delimited list of node names
      set_fact: 
        node_list: "{{ groups['all'] | join(',') }}"

    - name: Test if /storage exists
      command: ls /storage
      register: storagedir
      ignore_errors: true
    - name: Create /storage directory
      file:
        path: /storage
        state: directory
      when: storagedir is failed

    - name: Mount CephFS volume
      ansible.posix.mount:
        path: /storage
        src: "{{ node_list }}:/"
        fstype: ceph
        opts: name=admin,noatime,_netdev
        state: mounted

- name: node-mount-fs
  hosts: workers
  become: yes
  tasks:
    - name: Create commad-delimited list of node names
      set_fact: 
        node_list: "{{ groups['all'] | join(',') }}"

    - name: Test if /storage exists
      command: ls /storage
      register: storagedir
      ignore_errors: true
    - name: Create /storage directory
      file:
        path: /storage
        state: directory
      when: storagedir is failed

    - name: Mount CephFS volume
      ansible.posix.mount:
        path: /storage
        src: "{{ node_list }}:/"
        fstype: ceph
        opts: name=admin,noatime,_netdev
        state: mounted