- name: Assign Swarm node labels
  hosts: manager
  become: yes
  tasks:
    - name: Assign Docker Swarm node task role labels
      command: docker node update --label-add tasks={{ hostvars[item].swarm_job }} {{ item }}
      loop: "{{ groups['all'] }}"

- name: Install some common tools
  hosts: all
  become: yes
  tasks:
    - name: Install some common tools
      dnf:
        name: "{{ packages }}"
      vars:
        packages:
          - nano
          - bash-completion
          - htop
          - git