apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: inetfa
      protocol: layer2
      addresses:
      - 10.1.10.31/32